[bigquery]
project_id = "cis-4400-457114"
dataset = "parking_and_311_staging"

[tables]
agency_dim = "dim_agency"
complaint_dim = "dim_complaint"
date_dim = "dim_date"
fact_311_complaints = "fact_311_complaints"
fact_parking_tickets = "fact_parking_tickets"
integrated_fact_service_requests = "integrated_fact_service_requests"
location_dim = "dim_location"
parking_location_dim = "dim_parking_location"
time_dim = "dim_time"
vehicle_dim = "dim_vehicle"
violation_dim = "dim_violation"
